version: '3'

services:
  fastview-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2020!"
    ports:
      - "5432:5432"
    volumes:
      - ~/backend-nestjs/postgres-docker/bin/PostgreSQL:/var/lib/postgresql/data 
    networks:
      - postgres-compose-network
      
networks: 
  postgres-compose-network:
    driver: bridge